### ISSUE TITLE
[Enhancement] Make client display prettier

### ISSUE THREAD

**Issue by phinocio** [phinocio/go_chat#3]
Right now the client display of messages is kinda bleh and received messages clobber input until typing. Make it prettier :D :eyes:

**Comment by invae** [comment]
resolved in cab43c6d20899611a9898eeb389602bd0d4a1d20.

single message are now less obnoxious in the client's tui

**Comment by invae** [comment]
![image](https://github.com/phinocio/go_chat/assets/95193758/b2c7b1c7-3b61-4c65-a34b-7fe369712c3b)

example execution, alice receives message from bob
